### ISSUE TITLE
rewrite architecture discussion

### ISSUE THREAD

**Issue by Holger-Will** [enocean-js/enocean-js#1]

**Comment by Holger-Will** [comment]
moving to mono repository design. we need tools in place to mange that. I 
'm currently looking at https://github.com/lerna/lerna

**Comment by Holger-Will** [comment]
alternatively we can follow [pouchDBs example](https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4) and drop management tools all together and follow the ["Alle"](https://github.com/boennemann/alle) proposal

**Comment by Holger-Will** [comment]
we should go with synced versioning. all modules allways have the same version.

**Comment by Holger-Will** [comment]
i went ahead setting up the repo by the "alle" principle... lets see how this works out...

**Comment by RafaelKa** [comment]
> we should go with synced versioning. all modules always have the same version.

Note: "Lernas fixed mode" https://github.com/lerna/lerna#fixedlocked-mode-default

**Comment by Holger-Will** [comment]
now that versioning and publishing scripts are in place we should document how to do things here. `CONTRIBUTING.md` seems a good place for that.

**Comment by Holger-Will** [comment]
I'm implementing the interfaces, so that instantiation happens in a .from method. that should be consistent across all objects. f.e.

    ESP3Packet.from()
    Response.from()

i think this looks, reads and writes much nicer and is semantically more correct than

    makeESP3Packet()
    makeResponse() // that sounds just wrong for parsing responses we get...

**Comment by Holger-Will** [comment]
there is now a simple websocket server (in @enocean-js/websocket-gateway)

if you run that with `node -r esm server.js` it will listen on the serialport for telegrams and will forward them as strings to every browser that connects to localhost:3000.

now you can run a second server, that serves some html, that connects to the gateway.
Insed the browser you can use every module of the enocean lib that you can use in node (besides the serialport stuff).

you can then ESP3packet.from(string_from_socket_io) and do whatever.

the common command interface works as well.You can pass a sender implementation to  commonCommand.connect() which implements the .send() method. there two sender impelemtations:

* SerialportSender
* WebsocketSender

whe inside a browser, you can do:

    import { CommonCommand } from '/node_modules/@enocean-js/common-command/src/CommonCommand.js'
    import { WebsocketSender } from '/node_modules/@enocean-js/websocket-sender/src/websocket-sender.js'
      var socket = io('http://localhost:3000');
      var sender = WebsocketSender(socket)
      var commander = CommonCommand.connect(sender)

then the commander behaves the same in the broswser as it does in node.

    await commander.setBaseId("ff800000")
    console.log( await commander.getBaseId() )

etc. ... you can even read and write raw memory data of your TCM device.

**Comment by Holger-Will** [comment]
![screenshot_20181217_171409](https://user-images.githubusercontent.com/10807348/50099805-3ea8c380-021f-11e9-8a3e-e667d83226dd.png)

**Comment by RafaelKa** [comment]
@Holger-Will just check this out: https://wamp-proto.org/

**Comment by Holger-Will** [comment]
i remember having looked at WAMP a few years ago, but completely forgot about it. It looks like we should go with this. I will have a more detailed look at this in the nex few days...

First  i'd like to have the basic functionality in place ... at least Radio_ERP1 and some EEPs should be done.

**Comment by Holger-Will** [comment]
i'm not happy with the way packet creation is currently implemented. i'd really like to take a more functional approach.

the CommonCommand.connect method tries to be too much at the same time. packet creation and convienient functions are too tightly coupled. 

I'm quite please up to the esp3Packet part. but for both the parsing and creation of concrete packets i'm still not sure how the API should look like.

any ideas, preferences?

**Comment by Holger-Will** [comment]
there is now an installable package.

    npm i -S enocean-js

see the readme for an example.

there is also a bundle usable in the browser.

https://cdn.jsdelivr.net/npm/enocean-js@0.0.1-beta.8/packages/enocean.js

i will add a few examples later today
