### ISSUE TITLE
Node 10 compatibility?

### ISSUE THREAD

**Issue by spants** [enocean-js/enocean-js#102]
The nodes seem to hang when using node v10 but work great on node v8..... Are there any plans to migrate them?.

**Comment by Holger-Will** [comment]
the library itself is tested countinously on the latest version of node.js ( current build passes with node 11.5 ) ... though there are currently no test for node-red yet... i'll have to check. But i don't see why this would not work on node 10...

**Comment by Holger-Will** [comment]
mmh... just tested with node 11.14, everything works well... have you changed your node version recently? you might have to `npm rebuild` ...

**Comment by spants** [comment]
Will try again. I'm using the official node Red docker with the v10 tag. It worked for a couple of devices then became unresponsive. 
Using USB serial device pass through.

Thanks for looking at it!

**Comment by Holger-Will** [comment]
mmhh... could be a memory problem. still early beta ;-) i use a lot of event listeners and i'm not sure they are all removed properly... can you test memory consumption in your setup while it becomes unresponsive?
