### ISSUE TITLE
[NRCE] Input node for all devices?

### ISSUE THREAD

**Issue by spants** [enocean-js/enocean-js#103]
Thanks for your work on this. I have lots of enocean devices and it seems that I need a node for each one.

For the future, could I assign multiple devices to one node? Say add all switches to one, temperature devices to another etc.... Or maybe all just to one node?

Thanks again

**Comment by Holger-Will** [comment]
there is currently an output node for a button and a general output node for everything else.
the rational behind this was that this way it's easy to manage channels and eeps. but i don't see we couldn't have an output node where you can pass channel and eep.

Maybe you can tell me something about your use case and how you imagine it could be used, and i can build a prototype for this.

**Comment by spants** [comment]
I have a number of devices and was wondering if there was one node that I could connect all of my logic to. 
It's not important though..  i can pipe all the individual nodes to one set of function s

**Comment by Holger-Will** [comment]
are we talking about listening to multiple external devices? or simulating multiple devices devices internally and then sending the data?

**Comment by Holger-Will** [comment]
just published v0.4.3 based on your input.

moved the parser and transformer stream to the config node, so these are now shared between all nodes, and the single nodes just listen to the stream. that should prevent the sowing down and be much more scaleble.

before we had 2 transform streams per node, now we just to for the whole flow.

**Comment by Holger-Will** [comment]
i thougth about the "one node for all inputs" idea for a bit, and it might allow for more powerful flows for the cost of higher complexity.
I'm still not sure how to handle the teach in and management of the EEPs in that case...
I#m open for ideas though... it will have to wait until v1.0.0

**Comment by Holger-Will** [comment]
there is now an output node available for all devices... still thinking about the input...

**Comment by Holger-Will** [comment]
What do you think about separating the input node from the teach in altogether? 

we could have a general input node, that forwards all telegrams, and teachable "device nodes" that connect to that node? 

this way you can implement your own teach in logic, group sensors and logic etc.
the most important part though is that this will enable virtual devices with bidirectional communication...

**Comment by Holger-Will** [comment]
actively working on a rewrite of the input node as proposed with separated `input node` and `device node` which can hold one or more devices. it's a much more flexible architecture...

**Comment by Holger-Will** [comment]
currently with the old version i used the nodes context to save the sensor info, that has the disadvantage of requiring the user to change a node-red setting in order for it to work.

I now use the nodes config to store the information. The disadvantage here is that now you can not teach in sensors without implementing the flow each time a new sensor is tought in...

i will probably go with this approach for now anyways until i have a native memory in enocean-js in place.

**Comment by spants** [comment]
Back from travels.... It works really nicely as it is now. I will put in a request for passing the name of the input node in meta output as this could solve my use case!

**Comment by Holger-Will** [comment]
with `0.5.0-alpha.1 ` this should be fixed now
