### ISSUE TITLE
pass Name of input node to meta object with data

### ISSUE THREAD

**Issue by spants** [enocean-js/enocean-js#107]
I use MQTT as the transport protocol for messaging.
Currently I can have multiple Input nodes each connected to PIR sensors in a group. The outputs of these input nodes can share a common flow if it is easy to determine the source. Currently the "sender id" is output which will need to be converted (with a lookup table/function) to a 'friendly name' to use as an MQTT topic. As this 'friendly name' already exists as "Sender Name" - could this be sent as well?

If the "Sender Name" is sent, I could construct an mqtt topic such as house/pir/"Sender Name"

**Comment by Holger-Will** [comment]
No Problem I will implement that tonight

**Comment by Holger-Will** [comment]
fixed in 0.4.13

you will find the nodes name in `msg.meta.name`

**Comment by spants** [comment]
ah - you are not using the Name of the node.... just the name in the blue box for the device.... Can you please use the Node name as it makes it easier to change/see?

**Comment by Holger-Will** [comment]
there are two names now:

1) the node name, found in `msg.meta.actorName`
2) the name of each device found in `msg.meta.name`

**Comment by spants** [comment]
Great!, thanks
