### ISSUE TITLE
[NRCE] problem with eep a5-12-01 (pressac version of eep)

### ISSUE THREAD

**Issue by spants** [enocean-js/enocean-js#108]
(maybe related to #109) update *** not caused by 109 

This device (power clamp from pressac) does not get picked up when manually entering the eep on the input node.

If you do a teach/learn, the device is recognised and works until you do a redeploy.

A couple of sample msg when working:

{"payload":{"LRNB":{"name":"LRN Bit","unit":"","rawValue":1,"value":"1","description":"Data telegram"},"MR":{"name":"Meter reading","rawValue":14,"value":1.4000000000000001,"range":{"min":"0","max":"16777215"},"scale":{"ref":"DIV"},"unit":"W"},"TI":{"name":"Tariff info","rawValue":5,"value":5,"range":{"min":"0","max":"15"},"scale":{"min":"0","max":"15"},"unit":"1"},"DT":{"name":"Data type (unit)","unit":"W","rawValue":1,"value":"1","description":"Current value","scale":"1"},"DIV":{"name":"Divisor (scale)","unit":"","rawValue":1,"value":"1","description":"x/10","scale":{"min":"0","max":"1677721.5"}}},"meta":{"senderId":"01858d92","RORG":165,"eep":"a5-12-01","RSSI":67,"payload":"00000e5d","subTelNum":1,"raw":"55000a0701eba500000e5d01858d920001ffffffff430076","timestamp":1557134126915},"_msgid":"c349863e.36c178"}

{"payload":{"LRNB":{"name":"LRN Bit","unit":"","rawValue":1,"value":"1","description":"Data telegram"},"MR":{"name":"Meter reading","rawValue":19,"value":1.9000000000000001,"range":{"min":"0","max":"16777215"},"scale":{"ref":"DIV"},"unit":"W"},"TI":{"name":"Tariff info","rawValue":5,"value":5,"range":{"min":"0","max":"15"},"scale":{"min":"0","max":"15"},"unit":"1"},"DT":{"name":"Data type (unit)","unit":"W","rawValue":1,"value":"1","description":"Current value","scale":"1"},"DIV":{"name":"Divisor (scale)","unit":"","rawValue":1,"value":"1","description":"x/10","scale":{"min":"0","max":"1677721.5"}}},"meta":{"senderId":"01858d92","RORG":165,"eep":"a5-12-01","RSSI":67,"payload":"0000135d","subTelNum":1,"raw":"55000a0701eba50000135d01858d920001ffffffff430049","timestamp":1557134249297},"_msgid":"f516b65a.348e08"}

**Comment by Holger-Will** [comment]
what version of `node-red-contrib-enocean` do you use? there was a problem with entering adresses manually which is fixed with 0.4.12

**Comment by spants** [comment]
I'm using 0.4.12 .... the other eeps that I entered manually were ok (even though some said unknown EEP)

**Comment by Holger-Will** [comment]
ok, I will check...

**Comment by spants** [comment]
I deleted all the nodes except a couple to avoid the Listeners problem but this eep still gives the problem. The other gateway that I use notes that this eep is a "Pressac variation of a5-12-01" but I am unsure why in learn mode it works until a redeploy

**Comment by Holger-Will** [comment]
could you try to remove that particular node, and then have two nodes for the pressac sensor, one where you tech in automatically and the other where you put in that info manually, please?
I just want to make sure that the mixing of both teach in methods does not break things (again) ;-)

**Comment by Holger-Will** [comment]
I now do some more event listener clean up. with `0.5.0-alpha.1` this should be fixed... or at least it should be easier to debug.

**Comment by Holger-Will** [comment]
did you test this again with v0.5.0-alpha?

**Comment by spants** [comment]
Auto learn in works now - thanks. I cant see a way of doing a manual input though.

**Comment by Holger-Will** [comment]
manuell teach in works by sending an LRN message with the following content:

```
{
  "type": "LRN",
  "senderId": "00112233",
  "eep": "a5-02-03"
}
```
