### ISSUE TITLE
[NRCE] maxlisteners Exceed warning

### ISSUE THREAD

**Issue by spants** [enocean-js/enocean-js#109]
Error message in Node Red log - (maybe related to Issue #108)

(node:16) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

I have 9 enocean input nodes at the moment

I use NodeRed docker v0.20.5 and Nodejs version 8 with this instance.

**Comment by Holger-Will** [comment]
I find the error messages wording a bit strange... the enocean-input node does not register any error listeners... 

What it does though, each node adds an event listener to the config-nodes transformer stream. that could potentially be a problem.

In the dev branch, I have a completely new architecture: there will only be one input node. that will send out any received telegram as a message. you can then wire up nodes, where you can teach in the devices. That should solve the problem.
Additionally, it would be much easier to debug problems like the one you have with the pressac sensor because you could wire up a debug node to the raw input and compare that between the working and not working version...

**Comment by Holger-Will** [comment]
> I use NodeRed docker v0.20.5 and Nodejs version 8 with this instance.

I hope it's node >8.4.0 because that is the min version for enocean-js. if the version is <8.4.0 things will definitely break...

**Comment by spants** [comment]
Hi Holger
It is these versions:
6 May 16:58:50 - [info] Node-RED version: v0.20.5
6 May 16:58:50 - [info] Node.js version: v8.15.1

I will check out the dev branch in a couple of days - many thanks

**Comment by Holger-Will** [comment]
#103 will fix this

**Comment by Holger-Will** [comment]
> I will check out the dev branch in a couple of days - many thanks

it's not really usable yet... I try to get something you can work with done by the weekend. I'll let you know.

**Comment by Holger-Will** [comment]
ok just pushed the branch it's called `multisensor`... as I said, it's not yet usable...

**Comment by Holger-Will** [comment]
I've just release the first alpha with the new implementation. you have to explicitly install

`npm i -S node-red-contrib-enocean@0.5.0-alpha.0`

some things change to what I've written above. A lot of things will not work yet, and the documentation is completely wrong, but you can start testing it if you like... if you need a pointer at how to start, please ask here... else I will add some documentation and sample flows soon...

**Comment by Holger-Will** [comment]
Could it be that the maxListener error is triggered by doing many redeploys?

I do register error handlers with the config-node, and I don't remove these handlers when the node gets stopped and redeployed. If there are still some references around to each error handler, the garbage collector can not get rid of them... that's a classical memory leak when working with event listeners...

**Comment by Holger-Will** [comment]
I now do some more event listener clean up. with `0.5.0-alpha.1` this should be fixed

**Comment by spants** [comment]
0.5.0-alpha.2 seems to be ok. Can you change your naming?
Node Red Manage Palette sees 0.5.0-alpha1 and 0.5.0-alpha2 as the same so that you have to do a manual delete and install. Perhaps 0.5.1-alpha and 0.5.2-alpha could work for you and trigger the updates?

**Comment by Holger-Will** [comment]
geat this is fixed! thanks for testing so much! 

well, I wanted to start following [semver](https://semver.org/) with v0.5.0 

so, up until then, we want to be sure about the API... currently, I just do `npm version prerelease --preid=alpha`. We can switch to beta maybe...
when we leave the beta phase, we must be backward compatible up to 1.0.0!

so, what do you think about the current API?
