### ISSUE TITLE
UnhandledPromiseRejectionWarning - 0.5.0-alpha1

### ISSUE THREAD

**Issue by spants** [enocean-js/enocean-js#111]
Uninstalled 0.5.0-alpha and installed 0.5.0-alpha1 via Manage Palette....
Created a new actor, Injected LRN and duration which was picked up but no data flows from the actor.

In the NodeRed logging, I see the following:

(node:16) UnhandledPromiseRejectionWarning: TypeError: payload.getValue is not a function
at /data/node_modules/@enocean-js/eep-transcoder/src/eep-transcoder.js:189:28
at Array.reduce (<anonymous>)
at decodeCase (/data/node_modules/@enocean-js/eep-transcoder/src/eep-transcoder.js:180:25)
at decode (/data/node_modules/@enocean-js/eep-transcoder/src/eep-transcoder.js:167:5)
at RadioERP1.decode (/data/node_modules/@enocean-js/radio-erp1/src/radio-erp1.js:102:12)
at sensors.filter.forEach.item (/data/node_modules/node-red-contrib-enocean/nodes/enocean-actor.js:70:40)
at Array.forEach (<anonymous>)
at EnoceanActorNode.<anonymous> (/data/node_modules/node-red-contrib-enocean/nodes/enocean-actor.js:65:81)
at emitOne (events.js:116:13)
at EnoceanActorNode.emit (events.js:211:7)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 102)

**Comment by Holger-Will** [comment]
can you post your flow? and what eep did you try to teach in?

**Comment by Holger-Will** [comment]
I was able to reproduce the bug. I'm investigating... I can trigger it if there is more than one actor. can you confirm that this only happens in that case?

**Comment by spants** [comment]
I had two actors, I think..... I will check when I return home

**Comment by Holger-Will** [comment]
so node-red somehow messes up msg objects when forwarding them to other nodes... I don't know but I believe they are doing deep copies of passed objects and mess up the types. 

the basic data type in node-enocean is ByteArray, a class that inherits from object. it serializes to Array notation. 
on the second listener, all ByteArrays are plain Array missing the extra methods... that somehow points to serialization and wrong deserialization but I could be completely wrong...
I can not reproduce the error outside of node-red though, so I think it must be connected.

two possible solutions:

1) don't use ByteArray, but extend the Array Object (i don't like that)
2) deepFreeze the Object and see what happens...
3) pass real immutable Objects like strings around and convert to them to usable types on the fly (i think i will go with this)

**Comment by spants** [comment]
It might be a good idea to post on the node-red slack channel where nick oleary or dave cj can pick it up....

**Comment by Holger-Will** [comment]
yeah, but for that, I want to be absolutely sure the error is on their part...

**Comment by Holger-Will** [comment]
ok, so now I have an MCV triggering the bug that does not use enocean-js but only native nodes...

![image](https://user-images.githubusercontent.com/10807348/57542674-9cff4b80-7352-11e9-9bee-fa758e84b065.png)


`[{"id":"3f9bab72.f45d44","type":"function","z":"32bbe58d.19148a","name":"","func":"class MyArray extends Array{}\nclass MyThing {\n    constructor(){\n        this.arr = new MyArray()\n    }\n}\nvar thing = new MyThing()\n\nreturn {payload: thing};","outputs":1,"noerr":0,"x":470,"y":100,"wires":[["d5ae8f14.e3fb3","7abcddf.c434824"]]}]`

i'll try the forum...

**Comment by Holger-Will** [comment]
https://discourse.nodered.org/t/nested-types-get-messed-up-when-passed-to-more-than-one-node/11006

**Comment by Holger-Will** [comment]
it seems to fix this behavior on node-reds side is a complex  task, so fixing it on my end by passing strings around...
the disadvantage now is that the actor node currently only understands RadioERP1 messages, but that's an easy fix...
