### ISSUE TITLE
[NRCE] encrypted telegrams not supported

### ISSUE THREAD

**Issue by jeroenclaes77** [enocean-js/enocean-js#126]

**Comment by jeroenclaes77** [comment]
Hello,

I am using EnOcean Pi on a Raspberry Pi 3B+, and have an Enocean Window Contact (SDO-2-1-05) wich EEP is "D5-00-01".
I'm actually trying to learn the Sensor in Node Red. By injecting "Learn" nothing happens. When I first inject "manuell teach in", and then "LRN", I was sometimes able to proper read the decoded data, but by placing the sensor on it's definitive place, I always get the following error:

msg : string[75]
"received an unknown RORG (35 instead of d5) from a konwn Sensor (05822d73)."

or

msg : string[75]
"received an unknown RORG (30 instead of d5) from a konwn Sensor (05822d73)."


Because of that, it does not give me any output to see the state of the contact (open or close).

I attached the exported flow I'm using. Is there something I'm doing wrong, or could it be maybe because of the "Learn button" of the sensor pressed permanently while it's on it's definitive position?

I appriciate every help on this!

[flow learn sensor.txt](https://github.com/enocean-js/enocean-js/files/3194076/flow.learn.sensor.txt)

**Comment by Holger-Will** [comment]
mmhh... I just tested your flow with a `d5-00-01` device, and it works well for me... can you sand me a few things:

- a screenshot of the taught in device
- what version of node-red-contrib-enocean are you using?
- a raw telegram string from the device

then i might be able to help...

**Comment by jeroenclaes77** [comment]
Hey, thanks for the feedback.
So here is the information you asked me for:

- 
![actor node](https://user-images.githubusercontent.com/50720997/57987930-4697b880-7a88-11e9-8727-ed13b7075ebd.PNG)

- the version of node-red-contrib-enocean is currently 0.5.5 One week ago it was an earlier version, same problem with that one.

- here is some raw data of the sensor:

DOOR OPEN:
msg.payload : string[50]
"55000b070180305ebb06ed0705822d730002ffffffff5000b4"

DOOR CLOSED:
msg.payload : string[50]
"55000b070180303df0ded2ff05822d730002ffffffff520035"

**Comment by Holger-Will** [comment]
thanks for the info!
So this is an encrypted message. Encryption/Decryption is not yet supported.
Support for secure transport is definitely a goal for this project, but it is still a long way of. 
This won't fix any time soon so marking it as won't fix for the time beeing

**Comment by jeroenclaes77** [comment]
Okay, I taught the encryption/decryption was made by the Enocean Pi already.
I will look if there’s maybe another door sensor compatible with enocean wich don’t sends encryptet messages, or maybe you know one?

Thank you very much for your help, I’ll stay tuned for for the encryption/decryption support! :)

**Comment by Holger-Will** [comment]
usually, you can deactivate encryption on your device... which one do you have?

**Comment by jeroenclaes77** [comment]
It’s the NodOn SDO-2-1-05

https://nodon.fr/en/nodon/enocean-door-window-sensor/

I didn’t find anything on disabling it on the device, but I wonder if its maybe disacticated when the Learn button is not pressed permanently (wich is the case when it’s mounted)

**Comment by Holger-Will** [comment]
3.2.2 Switching between modes - STM 320 / STM 329
STM 320 / STM 329 can be switched from normal mode to secure mode and vice versa by
long press of the LRN Button.
The behaviour of the LRN button is following:
1. Button is pressed – LED flashes briefly Teach-in is performed according to the actual
mode.
2. Button is hold
a. If released in period < 10 seconds then actual mode is kept. No further action.
b. If hold for at least 10 seconds then the actual mode is changed (standard ->
secure or secure -> standard). LED flashes briefly. Teach-in is performed according to the actual (new) mode.
3. Button is released – no action.
Upon entry into secure mode, a secure teach-in telegram is sent by STM 320 / STM 329.
Please see Chapter 3.2.3 for details.

**Comment by jeroenclaes77** [comment]
Indeed this works! I ignored that its the STM inside, so I didn't look into that manual.
I changed the mode to standard and everything works fine for me.
I use it to control my radiators when the window is open or closed. I will put this project online soon when its finished so far.
So when one day secure mode is also supported I will test it with that too.
Thank you for your help!
