### ISSUE TITLE
[NRCE] Conditional Datafield Selection

### ISSUE THREAD

**Issue by CityOfArkham** [enocean-js/enocean-js#151]
Hi Holger,

can you help me to understand how to define conditional selection of datafields as used in e.g. A5-38-08?

I tried with the definition below, but had no luck.
```
{
 "meta": {
   "eep": "a5-38-08",
   "channel": 3,
   "condition" : "0x01",
   "type": "data"
 },
 "data": { 
   ...
 }
}
```

Thanks for your help!

BR,
Alex

**Comment by Holger-Will** [comment]
you are so close ;-) it's:

```
{
 "meta": {
   "eep": "a5-38-08",
   "channel": 3,
   "data" : 1,
   "type": "data"
 },
 "data": { 
   ...
 }
}
```
I know this is not documented and confusingly named. the reason is that there are multible different conditions: datafield ("data"), statusfield("status") and direction("direction")
i might change that syntax and wording in the future.

**Comment by CityOfArkham** [comment]
Perfect!
Thanks for the quick and helpful response!
