### ISSUE TITLE
Documentation / how to start

### ISSUE THREAD

**Issue by rollercontainer** [enocean-js/enocean-js#152]
Hi, 
thank you for programming enocean implementation for javascript. I appreciate it a lot!

I've got a 2 channel relay from NodOn and a USB300. I turned the relay into pairing mode and node-red received:
`{
    "payload": "550009070156d20460e405125bbd0001ffffffff3700cc",
    "meta": {
        "type": "radio-erp1",
        "rorg": 210,
        "senderId": "05125bbd",
        "destinationId": "ffffffff",
        "subTelNum": 1,
        "rssi": 55,
        "timestamp": 1564143342864,
        "status": 0
    },
    "_msgid": "52fb21e6.6d06e"
}`
How do I pair them and control the relay from node-red afterwards?

**Comment by Holger-Will** [comment]
here is an example flow for the nodeOn module... the module uses a bidirectional teach in method which makes it one of the more complex parts of the spec.

```
[{"id":"a5e956de.749b68","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"f23f04f5.51e628","type":"enocean-in","z":"a5e956de.749b68","serialport":"6f46a875.7265b8","name":"in","x":90,"y":80,"wires":[["ca588d44.5387d","eced4012.4e249"]]},{"id":"ca588d44.5387d","type":"enocean-actor","z":"a5e956de.749b68","name":"Aktor 1","channel":"10","x":280,"y":120,"wires":[["eced4012.4e249"],["fbdde8aa.bc7da8"]]},{"id":"539b496c.88c8c8","type":"inject","z":"a5e956de.749b68","name":"LRN","topic":"","payload":"{\"type\":\"LRN\",\"duration\":30}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":160,"wires":[["ca588d44.5387d"]]},{"id":"fbdde8aa.bc7da8","type":"enocean-out","z":"a5e956de.749b68","serialport":"6f46a875.7265b8","name":"","logOutput":true,"x":580,"y":160,"wires":[[]]},{"id":"fdc10fd0.cb5ff","type":"inject","z":"a5e956de.749b68","name":"on","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-12\",\"channel\":10,\"type\":\"data\",\"data\":1},\"data\":{\"CMD\":{\"value\":1},\"I/O\":{\"value\":30},\"OV\":{\"value\":100}}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":200,"wires":[["fbdde8aa.bc7da8"]]},{"id":"cb982957.07f248","type":"inject","z":"a5e956de.749b68","name":"off","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-12\",\"channel\":10,\"type\":\"data\",\"data\":1},\"data\":{\"CMD\":{\"value\":1},\"I/O\":{\"value\":0},\"OV\":{\"value\":0}}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":240,"wires":[["fbdde8aa.bc7da8"]]},{"id":"8b144f59.4041c","type":"inject","z":"a5e956de.749b68","name":"request state","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-12\",\"channel\":10,\"type\":\"data\",\"data\":3},\"data\":{\"CMD\":{\"value\":3},\"I/O\":{\"value\":30}}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":300,"y":280,"wires":[["fbdde8aa.bc7da8"]]},{"id":"da4ebd30.77203","type":"inject","z":"a5e956de.749b68","name":"request external interface","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-12\",\"channel\":10,\"type\":\"data\",\"data\":3},\"data\":{\"CMD\":{\"value\":12},\"I/O\":{\"value\":30}}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":320,"wires":[["fbdde8aa.bc7da8"]]},{"id":"1f9d94dc.02bb7b","type":"inject","z":"a5e956de.749b68","name":"delay off 2s","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-12\",\"channel\":10,\"type\":\"data\",\"data\":11},\"data\":{\"CMD\":{\"value\":11},\"I/O\":{\"value\":30},\"AOT\":{\"value\":20}}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":360,"wires":[["fbdde8aa.bc7da8"]]},{"id":"eced4012.4e249","type":"debug","z":"a5e956de.749b68","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":570,"y":80,"wires":[]},{"id":"6f46a875.7265b8","type":"enocean-config-node","z":"","serialport":"/dev/ttyUSB0"}]
```

**Comment by rollercontainer** [comment]
Something happened by putting both into pairing mode. I got this response:
`{
    "payload": {
        "PF": {
            "name": "Power Failure",
            "unit": "",
            "rawValue": 0,
            "value": "0b0",
            "description": "Power Failure Detection disabled/not supported"
        },
        "PFD": {
            "name": "Power Failure Detection",
            "unit": "",
            "rawValue": 0,
            "value": "0b0",
            "description": "Power Failure not detected/not supported/disabled"
        },
        "CMD": {
            "name": "Command ID",
            "unit": "",
            "rawValue": 4,
            "value": "0x04",
            "description": "ID 04"
        },
        "OC": {
            "name": "Over current switch off",
            "unit": "",
            "rawValue": 0,
            "value": "0b0",
            "description": "Over current switch off: ready / not supported"
        },
        "EL": {
            "name": "Error level",
            "unit": "",
            "rawValue": 3
        },
        "I/O": {
            "name": "I/O channel",
            "unit": "",
            "rawValue": 1,
            "min": "0x00",
            "max": "0x1D",
            "description": "Output channel (to load)",
            "value": 1
        },
        "LC": {
            "name": "Local control",
            "unit": "",
            "rawValue": 1
        },
        "OV": {
            "name": "Output value",
            "unit": "",
            "rawValue": 0,
            "value": "0x00",
            "description": "Output value 0% or OFF"
        }
    },
    "meta": {
        "type": "radio-erp1",
        "destinationId": "ffffffff",
        "subTelNum": 1,
        "rssi": 52,
        "timestamp": 1564227386263,
        "status": 0,
        "rorg": 210,
        "eep": "d2-01-12",
        "payload": "046180",
        "senderId": "05125bbd",
        "raw": "550009070156d204618005125bbd0001ffffffff34004d",
        "name": "",
        "actorName": "Aktor 1"
    },
    "_msgid": "be29c4e8.4ef5b8"
}`
How do I turn on and off Channel 1 and 2?

**Comment by Holger-Will** [comment]
here you can see all telegrams you can send to the device and what each value does.
https://enocean-js.github.io/enocean-js/?eep=d2-01-00

so basically to switch on/off you send cmd 1:
Where I/O value is the channel (0 or 1) and OV is the new value to switch to where 0 is off and 100 is on.

```
{
  "data": {
    "CMD": 1,
    "DV": 0,
    "I/O": 1, 
    "OV": 0 
  },
  "meta": {
    "eep": "d2-01-12",
    "channel": 10,
    "data": 1
  }
}

```

**Comment by rollercontainer** [comment]
Thank you very much! That link is the kind of source I was looking for. Maybe you should mention it in the readme.md. 
Closing ticket for now.

**Comment by Holger-Will** [comment]
added link to readme.md

**Comment by ptorrent** [comment]
Hey ! this is what I do :
```
var btn 				= Enocean.RadioERP1.from({ 
	rorg			: 210, 
	payload			: [0], 
	id				: baseId + 1
})
btn.destinationId 	= parseInt('059b72ed',16) 
btn.payload = btn.encode( {
	"CMD": 1,
	"DV": 0,
	"I/O": 0, 
	"OV": value 
},
 {
	"eep": "d2-01-00",
	"channel": 10,
	"data": 1
})
console.log(btn.toString())
 sender.send(btn.toString()).then(function(){
console.log('>>>>',arguments)
	callback()
 })
```

But nothing append on the actuator :(, any idea ?

**Comment by ptorrent** [comment]
How do you I turn the relay into pairing mode ?
