### ISSUE TITLE
Are Eltako FWZ12-65A and Eltako FBH65S (a5-08-01) working?

### ISSUE THREAD

**Issue by game4automation** [enocean-js/enocean-js#164]
Hi,

I have problems in getting the above Eltako sensors working. Even after learning the sensors, the telegrams don't get decoded by the actor node. Is this still in development or should it work?

Best regards
Thomas

**Comment by Holger-Will** [comment]
that should definitely work. can you post a raw telegram you get from the sensor here, please. I'll have a look at it.

**Comment by game4automation** [comment]
Thanks a lot. I think I learned the sensors right.

Here is the raw telegram of FBH65S:
![image](https://user-images.githubusercontent.com/48594799/72219789-1686b380-354a-11ea-962f-056ec7eee38a.png)

{"payload":"55000a0701eba5a900000d019aaf3a0001ffffffff580053","meta":{"type":"radio-erp1","rorg":165,"senderId":"019aaf3a","destinationId":"ffffffff","subTelNum":1,"rssi":88,"timestamp":1578836033952,"status":0},"_msgid":"e6014457.2843e8"}

And here the one of FWZ12-65A:
{"payload":"55000a0701eba50000470c008743160001ffffffff430011","meta":{"type":"radio-erp1","rorg":165,"senderId":"00874316","destinationId":"ffffffff","subTelNum":1,"rssi":67,"timestamp":1578837459265,"status":0},"_msgid":"646eda76.e63da4"}

I already thought that I need to decode the telegram by myself. Hope that this is not the case.

**Comment by Holger-Will** [comment]
can you also post a screenshot of your flow...

**Comment by game4automation** [comment]
here it is:
![image](https://user-images.githubusercontent.com/48594799/72244741-358b5100-35ef-11ea-9c9c-1cacc421c1a0.png)

**Comment by Holger-Will** [comment]
mmmhh... are you sure that what you see in the debug window is not the output of the debug-node connected directly to the input? you can inject a raw telegram string to an actor to test if it's working... try this flow, it works for me:

```
[{"id":"c8eb6860.94bfd8","type":"inject","z":"7c47f787.525138","name":"LRN","topic":"","payload":"{\"type\":\"LRN\",\"eep\":\"a5-08-01\",\"senderId\":\"019aaf3a\",\"name\":\"test1\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":610,"y":280,"wires":[["384657c7.376168"]]},{"id":"7ea25594.484d5c","type":"inject","z":"7c47f787.525138","name":"RAW","topic":"","payload":"55000a0701eba5a900000d019aaf3a0001ffffffff580053","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":610,"y":380,"wires":[["384657c7.376168"]]},{"id":"a5d3bc27.8fe21","type":"debug","z":"7c47f787.525138","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1010,"y":320,"wires":[]},{"id":"384657c7.376168","type":"enocean-actor","z":"7c47f787.525138","name":"","channel":1,"adt":false,"x":830,"y":320,"wires":[["a5d3bc27.8fe21"],[]]}]

```

**Comment by Holger-Will** [comment]
![image](https://user-images.githubusercontent.com/10807348/72408129-2f69b180-3762-11ea-989c-ac838b0c4447.png)

**Comment by game4automation** [comment]
This is strange. I removed the Debug node and added a new one and now it is working as expected. Sorry for my unnecessary ticket. Thanks a lot. Great work you did it will help to automate our new home
