### ISSUE TITLE
How to get device id from hex?

### ISSUE THREAD

**Issue by Jey-Cee** [enocean-js/enocean-js#167]
Is there a function to get the id of an device from the hex code of a telegram?

I have this (comes from the parser):
55000707017af600002782032000ffffffff4a0050
And looking for the id (and other base information):
00278203

**Comment by Holger-Will** [comment]
not all ESP3Packets come from devices and hence not all of them have IDs. You can get the id (senderId) of the device from the RadioERP1 interface though, so from whatever the transformer returns.

```
transformer.on('data', async data => {
  console.log(data.senderId)
})
```

**Comment by Jey-Cee** [comment]
Thats exact what i am looking for. Thank you.
