### ISSUE TITLE
NodOn MSP-2-1-11 - teach-in and switch

### ISSUE THREAD

**Issue by HarterHorst** [enocean-js/enocean-js#211]
Hi all, 

i have an issue with a Nodon MSP-2-1-11 MicroSmartPlug. I setup two Raspberries. One with NodeRed to act as station and one wire wireless-tapping with node-enocean-utils. 

As far as I can see, the teach-in process works fine with the following flow.
```
[{"id":"63b8ffae.13378","type":"enocean-in","z":"e61a631f.a568c","serialport":"5319be61.fd501","name":"","x":190,"y":40,"wires":[["d28d2bc4.865758"]],"info":"Light and Blind Control - Application Style 1"},{"id":"d28d2bc4.865758","type":"enocean-actor","z":"e61a631f.a568c","name":"SmartPlugSwitch","channel":"0","adt":false,"x":510,"y":100,"wires":[["22849ea6.dd7cb2"],["4f1f6062.56c7c","ebc1e0d0.cac63"]]},{"id":"84f8126c.16454","type":"inject","z":"e61a631f.a568c","name":"LRN","topic":"","payload":"{\"type\":\"LRN\",\"duration\":10}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":100,"wires":[["d28d2bc4.865758"]]},{"id":"22849ea6.dd7cb2","type":"debug","z":"e61a631f.a568c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":750,"y":40,"wires":[]},{"id":"4f1f6062.56c7c","type":"debug","z":"e61a631f.a568c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":730,"y":120,"wires":[]},{"id":"ebc1e0d0.cac63","type":"enocean-out","z":"e61a631f.a568c","serialport":"5319be61.fd501","name":"","logOutput":false,"x":730,"y":160,"wires":[["a29e712f.b93a8"]]},{"id":"a29e712f.b93a8","type":"debug","z":"e61a631f.a568c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":890,"y":160,"wires":[]},{"id":"5319be61.fd501","type":"enocean-config-node","z":"","serialport":"/dev/ttyUSB0"}]
```
Log from 2nd Raspberry says:

````
==================================================================================================================================================================
[Summary]
- HEX                          |55 00 0D 07 01 FD D4 A0 01 46 00 0E 01 D2 05 82 F7 09 00 03 FF FF FF FF 3C 00 EF
- Packet Type                  |RADIO_ERP1 (Radio telegram)
- Device Name                  |Unknown
- Device ID                    |00000582F709
- Manufacturer                 |ID_RF
- EEP                          |D2-01-0E
- RORG                         |VLD Telegram
- FUNC                         |Electronic switches and dimmers with Energy Measurement and Local Control
- TYPE                         |Type 0x0E
- Data                         |Unknown
- Learn                        |true
- Known                        |false
- RSSI                         |-60 dBm
- CRC                          |invalid
------------------------------------------------------------------------------------------------------------------------------------------------------------------
[Telegram]
- Sync. Byte                   |55         |55
- Header                       |00 0D 07 01|
  - Data Length                |00 0D      |13 byte
  - Optional Length            |07         |7 byte
  - Packet Type                |01         |RADIO_ERP1 (Radio telegram)
- CRC8H                        |FD         |valid
- Data                         |D4 A0 01 ..|
  - R-ORG                      |D4         |Universal Teach-In EEP based (0xD4)
  - Data_DL                    |A0 01 46 ..|
    - Uni-bi-directional comm..|01         |Bidirectional communication (EEP opeartion)
    - EEP Teach-In-Response m..|00         |EEP Teach-In Response message expected
    - Request accepted         |02         |Request accepted, deletion of teach-in successful
    - Command identifier       |00         |EEP Teach-In Query
    - No. of individual chann..|01         |1
    - Manufacturer ID          |0046       |ID_RF
    - TYPE                     |0E         |0E
    - FUNC                     |01         |01
    - RORG                     |D2         |D2
  - Originator-ID              |05 82 F7 09|05 82 F7 09
  - Status                     |00         |Original sender, 0
- Optional Data                |03 FF FF ..|
  - SubTelNum                  |03         |3
  - Destination ID             |FF FF FF FF|FF FF FF FF
  - dBm                        |3C         |-60 dBm
  - SecurityLevel              |00         |0
- CRC8D                        |EF         |valid
==================================================================================================================================================================
[Summary]
- HEX                          |55 00 0D 07 01 FD D4 91 01 46 00 0E 01 D2 FF DE C8 00 80 02 05 82 F7 09 4D 00 52
- Packet Type                  |RADIO_ERP1 (Radio telegram)
- Device Name                  |Unknown
- Device ID                    |0000FFDEC800
- Manufacturer                 |ID_RF
- EEP                          |D2-01-0E
- RORG                         |VLD Telegram
- FUNC                         |Electronic switches and dimmers with Energy Measurement and Local Control
- TYPE                         |Type 0x0E
- Data                         |Unknown
- Learn                        |true
- Known                        |false
- RSSI                         |-77 dBm
- CRC                          |invalid
------------------------------------------------------------------------------------------------------------------------------------------------------------------
[Telegram]
- Sync. Byte                   |55         |55
- Header                       |00 0D 07 01|
  - Data Length                |00 0D      |13 byte
  - Optional Length            |07         |7 byte
  - Packet Type                |01         |RADIO_ERP1 (Radio telegram)
- CRC8H                        |FD         |valid
- Data                         |D4 91 01 ..|
  - R-ORG                      |D4         |Universal Teach-In EEP based (0xD4)
  - Data_DL                    |91 01 46 ..|
    - Uni-bi-directional comm..|01         |Bidirectional communication (EEP opeartion)
    - EEP Teach-In-Response m..|00         |EEP Teach-In Response message expected
    - Request accepted         |01         |Request accepted, teach-in successful
    - Command identifier       |01         |EEP Teach-In Response
    - No. of individual chann..|01         |1
    - Manufacturer ID          |0046       |ID_RF
    - TYPE                     |0E         |0E
    - FUNC                     |01         |01
    - RORG                     |D2         |D2
  - Originator-ID              |FF DE C8 00|FF DE C8 00
  - Status                     |80         |Original sender, 0
- Optional Data                |02 05 82 ..|
  - SubTelNum                  |02         |2
  - Destination ID             |05 82 F7 09|05 82 F7 09
  - dBm                        |4D         |-77 dBm
  - SecurityLevel              |00         |0
- CRC8D                        |52         |valid
````

But the following flow does not work:

````
[{"id":"52eac2fe.c69a5c","type":"inject","z":"e61a631f.a568c","name":"Turn on","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-0e\",\"destinationId\":\"0582f709\",\"type\":\"data\",\"channel\":1,\"data\":1},\"data\":{\"CMD\":1,\"DV\":0,\"I/O\":0,\"OV\":100}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":400,"wires":[["c43fd69f.ec72b8"]]},{"id":"dead6bee.ced738","type":"debug","z":"e61a631f.a568c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":440,"wires":[]},{"id":"c43fd69f.ec72b8","type":"enocean-out","z":"e61a631f.a568c","serialport":"5319be61.fd501","name":"Switch","logOutput":true,"x":450,"y":440,"wires":[["dead6bee.ced738"]]},{"id":"cacb3a39.b539d8","type":"inject","z":"e61a631f.a568c","name":"Turn off","topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-0e\",\"type\":\"data\",\"destinationId\":\"0582f709\",\"channel\":0,\"data\":1},\"data\":{\"CMD\":1,\"DV\":0,\"I/O\":0,\"OV\":0}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":460,"wires":[["c43fd69f.ec72b8"]]},{"id":"5319be61.fd501","type":"enocean-config-node","z":"","serialport":"/dev/ttyUSB0"}]
````

Here's the log from the 2nd Raspi:
````
[Summary]
- HEX                          |55 00 09 07 01 56 D2 01 00 64 FF DE C8 01 80 03 05 82 F7 09 4F 00 01
- Packet Type                  |RADIO_ERP1 (Radio telegram)
- Device Name                  |Unknown
- Device ID                    |0000FFDEC801
- Manufacturer                 |Unknown
- EEP                          |Unknown
- RORG                         |Unknown
- FUNC                         |Unknown
- TYPE                         |Unknown
- Data                         |Unknown
- Learn                        |Unknown
- Known                        |false
- RSSI                         |-79 dBm
- CRC                          |invalid
------------------------------------------------------------------------------------------------------------------------------------------------------------------
[Telegram]
- Sync. Byte                   |55         |55
- Header                       |00 09 07 01|
  - Data Length                |00 09      |9 byte
  - Optional Length            |07         |7 byte
  - Packet Type                |01         |RADIO_ERP1 (Radio telegram)
- CRC8H                        |56         |valid
- Data                         |D2 01 00 ..|
  - R-ORG                      |D2         |Variable length data telegram (0xD2)
  - Data_DL                    |01 00 64   |
  - Originator-ID              |FF DE C8 01|FF DE C8 01
  - Status                     |80         |Original sender, 0
- Optional Data                |03 05 82 ..|
  - SubTelNum                  |03         |3
  - Destination ID             |05 82 F7 09|05 82 F7 09
  - dBm                        |4F         |-79 dBm
  - SecurityLevel              |00         |0
- CRC8D            
````

I have the feeling that there is a total misunderstanding on my side how to use the nodes. 

Update:
There seems to be a problem with the teach-in. When I teach-in a physical rocker to the smartswitch the light (the one that indicates that the SmartSwitch is in the learning mode) stops flashing instantly after I pressed a button on the rocker. When I tech-in via nodeRed the light continues to flash even after the actor node displays the device.

Update 2:
I did some teach-in of the SmartSwitch with FHEM and it worked instantly. I traced the communication and compared the telegrams. They are totally the same except one byte. It is the "SubTelNum" Byte. FHEM value is 0. NodeRed Value is 3. I'm not sure if I understand the SubTelNum (No. of subtelegrams) correct, but I thing that the Switch expects more telegrams from NodeRed. Is there a way to manipulate the value?

Update 3:
I have discovered a difference between the telegram content reported by NodeRed in the Debug node and the data sniffed with the 2nd Raspi. 

The NodeRed Debug node after the output node lists the following payload
````
55 00 0D 07 01 FD D4 91 01 46 00 0E 01 D2 FF DE C8 00 **00** 03 05 82 F7 09 FF 00 31
````
My sniffer reports 
````
55 00 0D 07 01 FD D4 91 01 46 00 0E 01 D2 FF DE C8 00 **80** 03 05 82 F7 09 4C 00 98. 
````
As you can see, one relevant byte is different. The 19th byte indicates a status. I currently do not understand what that is. But still, as stated above, the 20th byte (SubTelNo) should be 0 instead of 3 for the teach-in response to work with the device. 

I don't know why the debug node reports different data then the data actually transmitted over the air. 

Possible explanations are:

a) My sniffing station is not sniffing right.
b) The serial interface changes the data received from the output node.
c) something else.
 
Horst

**Comment by Holger-Will** [comment]
per spec: `SubTelNum 0xnn Number of subtelegram; Send: 3 / receive: 0`

so subTelNum is set to "3" when sending, when you receive that same telegram subTelNum should be "0". If you don't set subTelNum to 3 when sending, the USB stick refuses to send the package...
in node-red you see the telegram pre-sending, so the difference is expected.

**Comment by Holger-Will** [comment]
> Status: Telegram control bits – used in case of
> repeating, switch telegram encapsulation,
> checksum type identification

the Status byte is set by repeaters (in the case of VLD and UTE telegrams) thats why you see different values for sending and receiving

**Comment by Holger-Will** [comment]
unfortunately i do not have access to my ony device that supports UTE so i can not test at the moment :-(

**Comment by Holger-Will** [comment]
p.s.: your flow looks correct to me...

**Comment by Horst4711** [comment]
Pretty close to the first birthday of this issue, I tried again. And I failed again but this time with new information. Total new installation of raspi, NodeRed etc. When I teach-in the MicroSmartPlug I get the following dump on the NR-console.

Any (new) ideas?

Horst

`Feb 15 17:20:10 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: TypeError: Class constructor ByteArray cannot be invoked without 'new'
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at initCloneArray (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1235:22)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:854:14)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: TypeError: Class constructor ByteArray cannot be invoked without 'new'
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at initCloneArray (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1235:22)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:854:14)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
`

**Comment by HarterHorst** [comment]
Pretty close to the first birthday of this issue I tried again and failed again. But this time with new information. Clean setup, latest raspi, latest NR etc. When I try to teach-in I get the following dump on the NR-console.

`
Feb 15 17:20:10 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: TypeError: Class constructor ByteArray cannot be invoked without 'new'
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at initCloneArray (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1235:22)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:854:14)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:10 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:10 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: TypeError: Class constructor ByteArray cannot be invoked without 'new'
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at initCloneArray (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1235:22)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:854:14)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at baseClone (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at /usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Feb 15 17:20:13 raspi-test-1 Node-RED[368]:     at arrayEach (/usr/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Feb 15 17:20:13 raspi-test-1 Node-RED[368]: (node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
`

**Comment by HarterHorst** [comment]
Pretty close to the first birthday of this issue I think we can close it. After some month I have picked up the switch again last week and, to my surprise, gained sufficient motivation to solve this issue. It was a hard ride but (as always) I have learned a lot around EnOcean and node.js as well. 

1. Spot the differences

Last year the teach-in with enocean,js via nodered never worked. But due to the lack of knowledge around node.js I was not able to dig deeper into this. I tried to teach-in the device with fhem and it worked instantly. The I sniffed the packets and found out that the answer packet to the UTE request differs from fhem to enocean.js. 

// SubTelNum //

Value from fhem		: 0x01
Value from enocean.js	: 0x03

// Status Byte //

Value from fhem		: 0x8f
Value from enocean.js	: 0x00

As far as I understand the specifications, the SubTelNum should be x03 and the Status Byte should be 0x00. So nothing wrong the enocean.js. I just wonder how fhem managed to teach-in this device instantly. But anyway.
 
Maybe this is also the reason why I never managed to teach-in the switches to EnOcean - KNX Gateways like the ones from Weinzierl.

2. Manual Teach-in via script

Knowing the differences of the UTE answer gave me the knowledge to use the manualUTE.js script using different values for SubTelNum and Status Byte. I added some lines to transmit different SubTelNum and Status and to my surprise it worked instantly. The switch learned the host address and teach-in was complete. Wow.

I added line 4 and 5.

```
ret.payload = ret.payload.setValue(1, 0, 1) // bidi
ret.payload = ret.payload.setValue(1, 2, 2) // teach in successful
ret.payload = ret.payload.setValue(1, 4, 4) // this is a teach in response
ret.optionalData = [1,'0582f709', 'ff' , 0] // SubTelNum, Destination ID, dBM, SecurityLevel
ret.status = ['8f']
console.log('Response: ' + ret.toString())
```

3. Adding the device to context file

In order to make nodered to use the device I had to add the parameter to the context data file manually.

cd ~/.node-red/context/ea8f3582.<whatever>
edit d28d2bc4<whatever>

{
"senderId": "0582f709",
"eep": "d2-01-0e",
"rssi": 49,
"direction": 1,
"name": "Nodon Micro Smart Switch"
}

Remark: I ran into a problem with tabs in the file. so if you like to have it the same style as the existing ones, use space.

4. Writing the nodes in nodered.

```
[{"id":"3f1b3b44.d32cf4","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"b90a9ed5.66705","type":"inject","z":"3f1b3b44.d32cf4","name":"Turn on","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-0e\",\"destinationId\":\"0582f709\",\"type\":\"data\",\"channel\":1,\"data\":1},\"data\":{\"CMD\":1,\"DV\":0,\"I/O\":0,\"OV\":100}}","payloadType":"json","x":150,"y":140,"wires":[["9f70b0a7.41a26"]]},{"id":"750ac1e6.c143e","type":"debug","z":"3f1b3b44.d32cf4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":510,"y":180,"wires":[]},{"id":"9f70b0a7.41a26","type":"enocean-out","z":"3f1b3b44.d32cf4","serialport":"5319be61.fd501","name":"Switch","logOutput":true,"x":350,"y":180,"wires":[["750ac1e6.c143e"]]},{"id":"e0b56a15.be2728","type":"inject","z":"3f1b3b44.d32cf4","name":"Turn off","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"meta\":{\"eep\":\"d2-01-0e\",\"type\":\"data\",\"destinationId\":\"0582f709\",\"channel\":1,\"data\":1},\"data\":{\"CMD\":1,\"DV\":0,\"I/O\":0,\"OV\":0}}","payloadType":"json","x":150,"y":200,"wires":[["9f70b0a7.41a26"]]},{"id":"5319be61.fd501","type":"enocean-config-node","serialport":"/dev/ttyUSB0"}]

```

5. I will try to get in touch with Nodon Support. Maybe they have changed the protocol in the meantime and I can use it in other projects.
