### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by stab59** [enocean-js/enocean-js#214]
Hello, I'm trying to install this package but I'm getting an error. Here is the logs file :  

> -----------------------------------------------------------
> 2020-03-31T16:18:13.182Z Install : node-red-contrib-enocean 0.8.1
> 
> 2020-03-31T16:18:14.004Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-enocean@0.8.1
> 2020-03-31T16:18:16.946Z [err] npm
> 2020-03-31T16:18:16.946Z [err]  
> 2020-03-31T16:18:16.947Z [err] WARN
> 2020-03-31T16:18:16.947Z [err]  
> 2020-03-31T16:18:16.947Z [err] deprecated
> 2020-03-31T16:18:16.947Z [err]  mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
> 2020-03-31T16:18:22.032Z [out] 
> 2020-03-31T16:18:22.032Z [out] > @serialport/bindings@2.0.8 install /root/.node-red/node_modules/@serialport/bindings
> 2020-03-31T16:18:22.032Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
> 2020-03-31T16:18:22.032Z [out] 
> 2020-03-31T16:18:23.217Z [err] prebuild-install
> 2020-03-31T16:18:23.217Z [err]  
> 2020-03-31T16:18:23.218Z [err] WARN
> 2020-03-31T16:18:23.218Z [err]  
> 2020-03-31T16:18:23.218Z [err] install
> 2020-03-31T16:18:23.218Z [err]  No prebuilt binaries found (target=13.12.0 runtime=node arch=x64 libc= platform=linux)
> 2020-03-31T16:18:24.369Z [err] gyp
> 2020-03-31T16:18:24.369Z [err]  
> 2020-03-31T16:18:24.370Z [err] ERR!
> 2020-03-31T16:18:24.370Z [err]  
> 2020-03-31T16:18:24.370Z [err] build error
> 2020-03-31T16:18:24.370Z [err]  
> 2020-03-31T16:18:24.371Z [err] gyp
> 2020-03-31T16:18:24.372Z [err]  
> 2020-03-31T16:18:24.372Z [err] ERR!
> 2020-03-31T16:18:24.372Z [err]  
> 2020-03-31T16:18:24.372Z [err] stack
> 2020-03-31T16:18:24.372Z [err]  Error: not found: make
> 2020-03-31T16:18:24.372Z [err] gyp
> 2020-03-31T16:18:24.372Z [err]  
> 2020-03-31T16:18:24.373Z [err] ERR!
> 2020-03-31T16:18:24.373Z [err]  
> 2020-03-31T16:18:24.373Z [err] stack
> 2020-03-31T16:18:24.373Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
> 2020-03-31T16:18:24.373Z [err] gyp
> 2020-03-31T16:18:24.373Z [err]  
> 2020-03-31T16:18:24.373Z [err] ERR!
> 2020-03-31T16:18:24.373Z [err]  
> 2020-03-31T16:18:24.374Z [err] stack
> 2020-03-31T16:18:24.374Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
> 2020-03-31T16:18:24.374Z [err] gyp
> 2020-03-31T16:18:24.374Z [err]  
> 2020-03-31T16:18:24.374Z [err] ERR!
> 2020-03-31T16:18:24.374Z [err]  
> 2020-03-31T16:18:24.374Z [err] stack
> 2020-03-31T16:18:24.374Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
> 2020-03-31T16:18:24.375Z [err] gyp
> 2020-03-31T16:18:24.375Z [err]  
> 2020-03-31T16:18:24.375Z [err] ERR!
> 2020-03-31T16:18:24.375Z [err]  
> 2020-03-31T16:18:24.375Z [err] stack
> 2020-03-31T16:18:24.375Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
> 2020-03-31T16:18:24.375Z [err] gyp
> 2020-03-31T16:18:24.376Z [err]  
> 2020-03-31T16:18:24.377Z [err] ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> 2020-03-31T16:18:24.377Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> 2020-03-31T16:18:24.377Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:171:21)
> 2020-03-31T16:18:24.377Z [err] gyp ERR! System Linux 4.9.0-12-amd64
> 2020-03-31T16:18:24.377Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> 2020-03-31T16:18:24.377Z [err] gyp ERR! cwd /root/.node-red/node_modules/@serialport/bindings
> 2020-03-31T16:18:24.377Z [err] gyp ERR! node -v v13.12.0
> 2020-03-31T16:18:24.377Z [err] gyp ERR! node-gyp -v v5.1.0
> 2020-03-31T16:18:24.377Z [err] gyp ERR! not ok 
> 2020-03-31T16:18:24.980Z [err] npm
> 2020-03-31T16:18:24.980Z [err]  
> 2020-03-31T16:18:24.980Z [err] ERR!
> 2020-03-31T16:18:24.980Z [err]  
> 2020-03-31T16:18:24.980Z [err] code
> 2020-03-31T16:18:24.980Z [err]  ELIFECYCLE
> 2020-03-31T16:18:24.981Z [err] npm
> 2020-03-31T16:18:24.981Z [err]  
> 2020-03-31T16:18:24.981Z [err] ERR!
> 2020-03-31T16:18:24.981Z [err]  
> 2020-03-31T16:18:24.981Z [err] errno
> 2020-03-31T16:18:24.981Z [err]  1
> 2020-03-31T16:18:24.984Z [err] npm
> 2020-03-31T16:18:24.984Z [err]  
> 2020-03-31T16:18:24.984Z [err] ERR!
> 2020-03-31T16:18:24.985Z [err]  @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
> 2020-03-31T16:18:24.985Z [err] npm
> 2020-03-31T16:18:24.985Z [err]  
> 2020-03-31T16:18:24.985Z [err] ERR!
> 2020-03-31T16:18:24.985Z [err]  Exit status 1
> 2020-03-31T16:18:24.986Z [err] npm
> 2020-03-31T16:18:24.986Z [err]  
> 2020-03-31T16:18:24.986Z [err] ERR!
> 2020-03-31T16:18:24.986Z [err]  
> 2020-03-31T16:18:24.986Z [err] npm
> 2020-03-31T16:18:24.986Z [err]  
> 2020-03-31T16:18:24.987Z [err] ERR!
> 2020-03-31T16:18:24.987Z [err]  Failed at the @serialport/bindings@2.0.8 install script.
> 2020-03-31T16:18:24.987Z [err] npm
> 2020-03-31T16:18:24.987Z [err]  
> 2020-03-31T16:18:24.987Z [err] ERR!
> 2020-03-31T16:18:24.988Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
> 2020-03-31T16:18:25.006Z [err] 
> 2020-03-31T16:18:25.006Z [err] npm
> 2020-03-31T16:18:25.007Z [err]  
> 2020-03-31T16:18:25.007Z [err] ERR!
> 2020-03-31T16:18:25.007Z [err]  A complete log of this run can be found in:
> 2020-03-31T16:18:25.007Z [err] npm
> 2020-03-31T16:18:25.007Z [err]  
> 2020-03-31T16:18:25.007Z [err] ERR!
> 2020-03-31T16:18:25.007Z [err]      /root/.npm/_logs/2020-03-31T16_18_25_001Z-debug.log
> 2020-03-31T16:18:25.023Z rc=1

Could you help me?

**Comment by Holger-Will** [comment]
node-gyp seems to not have all dependencies installed to be able to build `node-serialport`... 

first try to install the new version `node-red-contrib-enocean@0.8.4`, this uses node-serialport@8.x which should come with prebuild binarys...

if that fails, install all required build tools on your system:

```
sudo apt-get install build-essential
```

**Comment by stab59** [comment]
It works ! I installed build tools on my system. 
Thank you
