### ISSUE TITLE
no data in data

### ISSUE THREAD

**Issue by Alaric84** [enocean-js/enocean-js#215]
right now I have the issue that there is nothin within the data object:
`pi@raspberrypi:~ $ node manualUTE.js  
[2020-04-13 17:19:51.839]  --- start ---  
[2020-04-13 17:20:07.125]  --- new Data! --- 
[2020-04-13 17:20:07.126]  ERP1
[2020-04-13 17:20:07.127]  Data: 
[2020-04-13 17:20:07.129]  Data telegram`

with the basic programming:
`transformer.on('data', async data => {
  console.log('--- new Data! --- ')
  if (data && data.constructor.name === 'RadioERP1') {
    console.log('ERP1')
    console.log('Data: ' + data.toString())
    if (data.teachIn) {`

on the same system I can receive messages within node-red.

versions are:
+ enocean-js@0.0.16
Node-RED version: v1.0.3
Node.js  version: v12.14.1

do you have any idea?

**Comment by pascalmartin** [comment]
I have the same problem

My solution was to remove the transformer and only use the parser

```javascript
const enoceanParser = new ESP3Parser();
port.pipe(enoceanParser); 
enoceanParser.on('data', async data => {
    if (data && data.constructor.name === 'RadioERP1') {
        Logger.log('info', 'ERP1')
    });
});
```

The transformer is made inside the parser [here](https://github.com/enocean-js/enocean-js/blob/aca3d2c1e31597b971cdf4bb6e940f30e574215d/packages/node_modules/%40enocean-js/serialport-parser/src/serialport-parser.js#L91)

I use this sample https://github.com/enocean-js/enocean-js/blob/master/examples/manualUTE.js and he misled me

**Comment by Alaric84** [comment]
Wow this solved my problem!
@Holger-Will So - this sample should definitelly be changed!

**Comment by Jean-PhilippeD** [comment]
Encountered the same problem, it was working with the transformer un version 0.0.14, now I updated to 0.1.0, I had to remove the transformer.

What is the purpose of this transformer ?
