### ISSUE TITLE
How to send a dimmer telegram ?

### ISSUE THREAD

**Issue by nabbl** [enocean-js/enocean-js#229]
Hey there,

@Holger-Will 

Currently I can only see that you can send a button value of 1 or 0 to either switch the actor off or on. How about a dimmer?

This worked fine one the old library where you were able to send a value like "50" to set the brightness to 50%.

Greetings

**Comment by nabbl** [comment]
This was in the old library and worked perfectly: https://github.com/enocean-js/node-enocean-dimmer

**Comment by Holger-Will** [comment]
yes that is still possible. you can use a5-38-08 for this.

```
 radio = RadioERP1.from({ payload: [0x00, 0x00, 0x00, 0x08] })
      radio.encode( {
        "COM": 2,
        "EDIM": brightness,
        "RMP": 1,
        "STR": 0,
        "SW": 1,
        "EDIM R": 0
    }, { eep: 'a5-38-08', data: 2 })
```

where brightness is a value between 0 and 100

**Comment by Holger-Will** [comment]
if you are using nede-red use a function node wried to the output node:

```
var telda = {
    "data": {
        "COM": 2,
        "EDIM": msg.payload,
        "RMP": 1,
        "STR": 0,
        "SW": 1,
        "EDIM R": 0
    },
    "meta": {
        "eep": "a5-38-08",
        "channel": 6,
        "data": 2
    }
}

return {payload: telda};
```

now you can send the brightness value to the function node in a msg.payload

**Comment by Holger-Will** [comment]
the helper objects i had in the old implementation are still missing, yes. but it was much harder to encode telegram then... now it is much simpler. writing a wrapper object for the dimmer should be quite simple...

**Comment by nabbl** [comment]
That worked just fine. Maybe a dedicated node would be cool anyway. thank you!
