### ISSUE TITLE
Sensorlist in enocean actor not working?

### ISSUE THREAD

**Issue by nabbl** [enocean-js/enocean-js#230]
I can see in the code that there should be a list of known sensors when looking at the enocean actor...
However no list is populated even though I have a sensor learned in successfully..

How is this supposed to work ?

**Comment by Holger-Will** [comment]
the list is stored in the contextStorage...

> **important!** for this nodes to work correctly you have to change the node-red setting for context stores.
> in settings.js set the contextStorage setting to localfilesystem

https://flows.nodered.org/node/node-red-contrib-enocean

...I know, it is not the best option, but the best I came up with at the time. I would prefer to store the list in the flow but that would mean you have to save the flow every time you teach in a sensor, which is quite inconvenient... maybe i can come up with something better...

**Comment by nabbl** [comment]
So you dont actually see the list on the node itself ? This was actually a nice feature in the old version because you were able to set which sensor to listen to on this node.

**Comment by Holger-Will** [comment]
you should see it in the actor as well...

**Comment by Holger-Will** [comment]
this is a client side script though... can you look into the browsers developer console to check if there are any error, please.
which browser do you use?

**Comment by nabbl** [comment]
Using the latest chrome. Problem is this:

`http://xxxxx:xxx/context/node/3b20fca9.e13634 401 (Unauthorized)`

**Comment by nabbl** [comment]
Ok got it to work. You are not allowed to have adminauthentication enabled...
