### ISSUE TITLE
Unable to install node-red-contrib-enocean

### ISSUE THREAD

**Issue by YomoShitsu** [enocean-js/enocean-js#244]
Hello I am actually unable to install this node on hassio for my home assistant. 
As suggested I changed the contextStorage in settings.js as localfilesystem 
It doesn't works...
Could you help me please ?
Thanks

**Comment by YomoShitsu** [comment]
Node-red is in version 10.0.0
And ha in 2021.9.6

**Comment by CSB92** [comment]
I have the same problem. Have you solved it?

**Comment by CSB92** [comment]
After 4 days of searching and testing i managed to install the enocean nodes in hassio.

You have to go to the node-red plugin and change in the configuration file the 
line 12 
system_packages: []
to  
system_packages: [linux-headers,gcc,g++,make,build-base]
then this system packages are enabled or installed and you can install the node-red-contrib-enocean in the webview.

**Comment by YomoShitsu** [comment]
Very very good job ! 
It works fine for me now !!!! 
Many thanks !

**Comment by YomoShitsu** [comment]
Hi @CSB92 after updating node red in v11.0.3, I am unbable to access to nodered webconsole.

`23 Feb 09:26:25 - [warn] ------------------------------------------------------
23 Feb 09:26:25 - [warn] [node-red-contrib-enocean/enocean-config-node] Error: The module '/config/node-red/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
23 Feb 09:26:25 - [warn] ------------------------------------------------------
23 Feb 09:26:25 - [info] Settings file  : /etc/node-red/config.js
23 Feb 09:26:25 - [info] Context store  : 'default' [module=memory]
23 Feb 09:26:25 - [info] User directory : /config/node-red/
23 Feb 09:26:25 - [warn] Projects disabled : editorTheme.projects.enabled=false
23 Feb 09:26:25 - [info] Flows file     : /config/node-red/flows.json
23 Feb 09:26:26 - [info] Server now running at http://127.0.0.1:46836/
23 Feb 09:26:26 - [debug] loaded flow revision: 4bd1f7dcc0ff65411a8b56f39fc6fe64
23 Feb 09:26:26 - [debug] red/runtime/nodes/credentials.load : user provided key
23 Feb 09:26:26 - [debug] red/runtime/nodes/credentials.load : keyType=user
[09:26:26] INFO: Starting NGinx...
23 Feb 09:26:26 - [info] Waiting for missing types to be registered:
23 Feb 09:26:26 - [info]  - enocean-config-node
23 Feb 09:26:26 - [info]  - www-request`

Could you help me please ?
