### ISSUE TITLE
clean up logo

### ISSUE THREAD

**Issue by Holger-Will** [enocean-js/enocean-js#3]
the logo was created by @huwylphi  see https://github.com/enocean-js/node-enocean/issues/27

it's graet to have it as an svg. I'm not a big fan of inskapes output though. in fact i'm not a fan of nay editors output. it would be nice to recreate the logo as clean and small as possible as handwritten svg.

**Comment by huwylphi** [comment]
FYI: the logo has been designed in [Vectr](https://vectr.com/) at the time (Jun, 2017)
https://vectr.com/huw/a1QAn7fTPt.svg?width=640&height=640&select=a1QAn7fTPtpage0

**Comment by Holger-Will** [comment]
the logo source look ok, it should use the pathes directly and not vie <use>
