### ISSUE TITLE
slack

### ISSUE THREAD

**Issue by Holger-Will** [enocean-js/enocean-js#4]
https://enocean-js.slack.com

**Comment by BitTourette** [comment]
invite link ?

**Comment by Holger-Will** [comment]
https://enocean-js.slack.com/signup I hope this works...

**Comment by BitTourette** [comment]
![slack invite](https://user-images.githubusercontent.com/6606285/50564184-48ecb680-0d23-11e9-9a1a-ca69ef118c85.png)
 
nope ;) bin leider kein klimapartner.de ;)

**Comment by Holger-Will** [comment]
das ließe sich ändern... wir suchen Kollegen... ;-) aber egal, der sollte es tun: https://join.slack.com/t/enocean-js/signup glaube ich...

**Comment by Holger-Will** [comment]
https://join.slack.com/t/enocean-js/shared_invite/enQtNTE0MzU2OTE1ODc2LTgzYTdhNDJkZWE3ZDk1MzVmYzk0NzcwZGVkMjNiMzg3MTU2MGNlNjEwYWVjNWNjYTcwZTNiOTdkZjk0NmYyOTU
