### ISSUE TITLE
add version update script

### ISSUE THREAD

**Issue by Holger-Will** [enocean-js/enocean-js#6]
the version update script should look into packages/node_modules/@enocean-js/* and update the package.json of all packages to the same version

**Comment by Holger-Will** [comment]
version script is in place. run `bin/version` to sync with root `package.json`
versioning is still done using `npm version` the script just syncs what you have done in root to all sub modules.

**Comment by Holger-Will** [comment]
version update script  SHOULD also update the dependencies of submodules.

**Comment by Holger-Will** [comment]
it should also update the version in the template package.json.

**Comment by Holger-Will** [comment]
ok... that's in place as well

**Comment by Holger-Will** [comment]
updated the version script. you use it like you would use npm version, and it automaticlly updates all lib packages, the template package.json and all lib dependencies.

**Comment by RafaelKa** [comment]
hehe there is a gift in script
https://github.com/enocean-js/enocean-js/blob/f87f7ac0c0517306787e01ab6eaf7b9799823906/bin/version#L36

**Comment by Holger-Will** [comment]
it's a package ;-)
