### ISSUE TITLE
publishing script

### ISSUE THREAD

**Issue by Holger-Will** [enocean-js/enocean-js#7]
we need a publishing script that goes into each package folder and does an `npm publish` there...

**Comment by RafaelKa** [comment]
Note: 
* `lerna publish` https://lernajs.io/#command-publish
* possible travis integration https://github.com/atlassian/lerna-semantic-release

**Comment by Holger-Will** [comment]
publication script is in place. publishes to @enocean-js scope. to publish a new version of all packeges do 


    npm version ...
    bin/version
    git commit -a -m "..."
    bin/publish
