### ISSUE TITLE
Issues parsing 'd2-50-00'

### ISSUE THREAD

**Issue by Alaric84** [enocean-js/enocean-js#82]
the parsing of values is way better
But is it possible to recognize unused values?
rawValue:0 seems to be a propper value - so its correct to scale it to -64 ... but its really not that cold here ;-)

```
  OUTT:
   { name: 'Outdoor Air Temperature',
     rawValue: 69,
     value: 5,
     range: { min: '0', max: '127' },
     scale: { min: '-64', max: '63' },
     unit: '°C' },
  SPLYT:
   { name: 'Supply Air Temperature',
     rawValue: 77,
     value: 13,
     range: { min: '0', max: '127' },
     scale: { min: '-64', max: '63' },
     unit: '°C' },
  INT:
   { name: 'Indoor Air Temperature',
     rawValue: 0,
     value: -64,
     range: { min: '0', max: '127' },
     scale: { min: '-64', max: '63' },
     unit: '°C' },
```

**Comment by Holger-Will** [comment]
> But is it possible to recognize unused values?

what does the field `RTCS` say? 

it is called "Room Temperature Control Status" it might be used by your device to indicate if the Indoor temperature sensor is present or not.

If that is the case, you would still have to implement the filtering logic yourself though :-(

**Comment by Alaric84** [comment]
hmmm I would not have read this from the specification but is says
```
  RTCS:
   { name: 'Room Temperature Control Status',
     unit: '',
     rawValue: 0,
     value: '0',
     description: 'room temperature control inactive' }
```
so you could be right.

I need to check if there is an "Room Temperature sensor" at all - or if it has to be activated.

**Comment by Holger-Will** [comment]
as per the spec you can not (at least not remotely) activate or deactivate it, so i guess that indicates the presents of an external room thermostat, which you could teach in to the ventilation device.
If you don't have one to test it, you could send telegrams (of eep a5-02-*) from a script... but you have to send a teach in telegram to your device first. But i guess that it's not UTE, we could try some things... we should really get the teach in implementation going ;-)

**Comment by Holger-Will** [comment]
The documentation says that the DL50WE2 supports a5-04-01 which sends temperature and humidity values. you could try to emulate an a5-04-01 device and teach that in to your DL50 and see what happens.

to send a teachin telegram to your device:

```
var ti = RadioERP1.makeTeachIn({
  type: '4BS',
  eep: "a5-04-01",
  senderId: baseId + 2
})
await sender.send(ti.toString())
```

and to send data mock up data:

```
radio = RadioERP1.from({ payload: [0x00, 0x00, 0x00, 0x08] })
radio.payload = radio.encode({HUM:50,TMP:22,TSN:1},{eep:"a5-04-01"})
await sender.send(radio.toString())
```

**Comment by Holger-Will** [comment]
i will close this now... if you have further questions, please feel free to reopen, or open a new issue.
